### ISSUE TITLE
DockerHub image produces a DBG message: Failed to authenticate HTTPS connection.

### ISSUE THREAD

**Issue by KamranVahdati** [OneIdentity/SafeguardDevOpsService#185]
When using the dockerhub image safeguard devops outputted a DBG message that wasn't in the docker container that was manually built.: 
2020-09-17 16:46:24.486 +00:00 [DBG] Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)

Full Output below:

2020-09-17 16:46:09.724 +00:00 [DBG] Hosting started
2020-09-17 16:46:09.724 +00:00 [DBG] Loaded hosting startup assembly SafeguardDevOpsService
2020-09-17 16:46:09.727 +00:00 [INF] The SafeguardDevOpsService service is now running, press Control+C to exit.
2020-09-17 16:46:24.294 +00:00 [DBG] Connection id "0HM2R54RBLKK0" accepted.
2020-09-17 16:46:24.295 +00:00 [DBG] Connection id "0HM2R54RBLKK0" started.
2020-09-17 16:46:24.482 +00:00 [DBG] Connection id "0HM2R54RBLKK0" received FIN.
2020-09-17 16:46:24.486 +00:00 [DBG] Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2020-09-17 16:46:24.502 +00:00 [DBG] Connection id "0HM2R54RBLKK0" stopped.
2020-09-17 16:46:24.507 +00:00 [DBG] Connection id "0HM2R54RBLKK0" sending FIN because: "The Socket transport's send loop completed gracefully."
2020-09-17 16:48:07.311 +00:00 [DBG] Connection id "0HM2R54RBLKK1" accepted.
2020-09-17 16:48:07.312 +00:00 [DBG] Connection id "0HM2R54RBLKK1" started.
2020-09-17 16:48:07.368 +00:00 [DBG] Failed to authenticate HTTPS connection.
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
2020-09-17 16:48:07.369 +00:00 [DBG] Connection id "0HM2R54RBLKK1" stopped.
2020-09-17 16:48:07.369 +00:00 [DBG] Connection id "0HM2R54RBLKK1" sending FIN because: "The Socket transport's send loop completed gracefully."
2020-09-17 16:48:07.421 +00:00 [DBG] Connection id "0HM2R54RBLKK2" accepted.
2020-09-17 16:48:07.421 +00:00 [DBG] Connection id "0HM2R54RBLKK2" started.
2020-09-17 16:48:07.524 +00:00 [INF] Request starting HTTP/2 GET https://10.5.37.237/service/devops/swagger/index.html
2020-09-17 16:48:07.585 +00:00 [INF] HTTP GET /service/devops/swagger/index.html responded 200 in 58.6799 ms
2020-09-17 16:48:07.591 +00:00 [INF] Request finished in 71.346ms 200 text/html;charset=utf-8
2020-09-17 16:48:07.671 +00:00 [INF] Request starting HTTP/2 GET https://10.5.37.237/service/devops/swagger/swagger-ui.css
2020-09-17 16:48:07.676 +00:00 [INF] Request starting HTTP/2 GET https://10.5.37.237/service/devops/swagger/swagger-ui-bundle.js
2020-09-17 16:48:07.676 +00:00 [INF] Request starting HTTP/2 GET https://10.5.37.237/service/devops/swagger/swagger-ui-standalone-preset.js
2020-09-17 16:48:07.864 +00:00 [INF] Sending file. Request path: '/swagger-ui.css'. Physical path: 'N/A'
2020-09-17 16:48:07.867 +00:00 [INF] HTTP GET /service/devops/swagger/swagger-ui.css responded 200 in 196.0433 ms
2020-09-17 16:48:07.983 +00:00 [INF] Request finished in 312.5955ms 200 text/css
2020-09-17 16:48:08.186 +00:00 [INF] Sending file. Request path: '/swagger-ui-standalone-preset.js'. Physical path: 'N/A'
2020-09-17 16:48:08.187 +00:00 [INF] HTTP GET /service/devops/swagger/swagger-ui-standalone-preset.js responded 200 in 510.9143 ms
2020-09-17 16:48:08.284 +00:00 [INF] Request finished in 607.8676ms 200 application/javascript
2020-09-17 16:48:08.469 +00:00 [INF] Sending file. Request path: '/swagger-ui-bundle.js'. Physical path: 'N/A'
2020-09-17 16:48:08.469 +00:00 [INF] HTTP GET /service/devops/swagger/swagger-ui-bundle.js responded 200 in 793.2760 ms
2020-09-17 16:48:08.470 +00:00 [INF] Request finished in 793.7322ms 200 application/javascript
2020-09-17 16:48:09.049 +00:00 [INF] Request starting HTTP/2 GET https://10.5.37.237/service/devops/swagger/v1/swagger.json
2020-09-17 16:48:09.102 +00:00 [INF] Request starting HTTP/2 GET https://10.5.37.237/service/devops/swagger/favicon-32x32.png
2020-09-17 16:48:09.103 +00:00 [INF] Sending file. Request path: '/favicon-32x32.png'. Physical path: 'N/A'
2020-09-17 16:48:09.103 +00:00 [INF] HTTP GET /service/devops/swagger/favicon-32x32.png responded 200 in 0.8477 ms
2020-09-17 16:48:09.103 +00:00 [INF] Request finished in 1.3023ms 200 image/png
2020-09-17 16:48:09.336 +00:00 [INF] HTTP GET /service/devops/swagger/v1/swagger.json responded 200 in 285.9141 ms
2020-09-17 16:48:09.336 +00:00 [INF] Request finished in 286.6138ms 200 application/json;charset=utf-8
2020-09-17 16:50:11.710 +00:00 [DBG] Connection id "0HM2R54RBLKK2" is closing.
2020-09-17 16:50:11.721 +00:00 [DBG] Connection id "0HM2R54RBLKK2" is closed. The last processed stream ID was 11.
2020-09-17 16:50:11.724 +00:00 [DBG] Connection id "0HM2R54RBLKK2" stopped.
2020-09-17 16:50:11.725 +00:00 [DBG] Connection id "0HM2R54RBLKK2" sending FIN because: "The Socket transport's send loop completed gracefully."

**Comment by bnicholesdell** [comment]
Unable to reproduce this issue with the latest docker hub image. Release-6.12.1.108
