### ISSUE TITLE
Unable to anonymously connect to XXX

### ISSUE THREAD

**Issue by rummens** [OneIdentity/SafeguardDevOpsService#455]
Hi there,

could you give me some pointers on figuring out what I am doing wrong. I deployed the Docker Hub container on an OpenShift cluster, created a Deployment, Service, PVC and Route to expose everything. Ran the container as priveleged to be safe, as this is just intial exploring.

The Service comes up okay and I can reach the Web UI, I also get forwarded to the OI Vault Appliance and can authenticate. However after that the Secret Broker UI greets me with the following error:
`Failed to contact Safeguard at '10.201.128.11': Unable to anonymously connect to 10.201.128.11, Error:`

I created a terminal to the Pod and validated that I can reach the appliance, which I can (used wget to do so). I had to ignore the cert, as this is of course not known to the container but I also didnt find a way to inject our cert chain. I also confirmed the same on the K8s node to be sure, the basic connection works fine. Can you give me any hints on further troubleshooting I could do? Could the missing cert be the issue, as http connections are disabled on the appliance.

Thanks a lot!

In the Logs I see this but it also doesnt add much more:
```
2024-03-15 18:21:16.275 +00:00 [DBG] Connection id "0HN252D58LMOD", Request id "0HN252D58LMOD:00000031": started reading request body.
2024-03-15 18:21:16.275 +00:00 [DBG] Connection id "0HN252D58LMOD", Request id "0HN252D58LMOD:00000031": done reading request body.
2024-03-15 18:21:16.276 +00:00 [DBG] Done attempting to bind parameter 'safeguardData' of type 'OneIdentity.DevOps.Data.SafeguardData'.
2024-03-15 18:21:16.276 +00:00 [DBG] Done attempting to bind parameter 'safeguardData' of type 'OneIdentity.DevOps.Data.SafeguardData'.
2024-03-15 18:21:16.276 +00:00 [DBG] Attempting to validate the bound parameter 'safeguardData' of type 'OneIdentity.DevOps.Data.SafeguardData' ...
2024-03-15 18:21:16.276 +00:00 [DBG] Done attempting to validate the bound parameter 'safeguardData' of type 'OneIdentity.DevOps.Data.SafeguardData'.
2024-03-15 18:21:16.504 +00:00 [ERR] Failed to contact Safeguard at '10.201.128.11': Unable to anonymously connect to 10.201.128.11, Error:
OneIdentity.SafeguardDotNet.SafeguardDotNetException: Unable to anonymously connect to 10.201.128.11, Error:
   at OneIdentity.SafeguardDotNet.Authentication.AnonymousAuthenticator..ctor(String networkAddress, Int32 apiVersion, Boolean ignoreSsl, RemoteCertificateValidationCallback validationCallback)
   at OneIdentity.SafeguardDotNet.Safeguard.Connect(String networkAddress, Int32 apiVersion, Boolean ignoreSsl)
   at OneIdentity.DevOps.Logic.SafeguardLogic.ConnectAnonymous(String safeguardAddress, Int32 apiVersion, Boolean ignoreSsl)
2024-03-15 18:21:16.505 +00:00 [ERR] Executed action: PUT /service/devops/v2/Safeguard = OneIdentity.DevOps.Exceptions.DevOpsException: 400 BadRequest
Failed to contact Safeguard at '10.201.128.11': Unable to anonymously connect to 10.201.128.11, Error:
2024-03-15 18:21:16.505 +00:00 [DBG] Request was short circuited at exception filter 'OneIdentity.DevOps.Attributes.UnhandledExceptionErrorAttribute'.
2024-03-15 18:21:16.506 +00:00 [INF] Executing JsonResult, writing value of type 'OneIdentity.DevOps.Exceptions.DevOpsExceptionMessage'.
2024-03-15 18:21:16.506 +00:00 [INF] Executed action OneIdentity.DevOps.Controllers.V2.SafeguardController.SetSafeguard (SafeguardDevOpsService) in 231.1302ms
2024-03-15 18:21:16.506 +00:00 [INF] HTTP PUT /service/devops/v2/Safeguard responded 400 in 232.0004 ms
2024-03-15 18:21:16.506 +00:00 [INF] Request finished HTTP/2 PUT https://safeguard-secret-broker-route-safeguard-secret-broker.apps.arc-openshift-demo.resources.dev1.arc.airbus.local/service/devops/v2/Safeguard application/json 53 - 400 - application/json;+charset=utf-8 232.2337ms
2024-03-15 18:23:27.648 +00:00 [DBG] Connection id "0HN252D58LMOD" is closing.
2024-03-15 18:23:27.657 +00:00 [DBG] Connection id "0HN252D58LMOD" is closed. The last processed stream ID was 49.
2024-03-15 18:23:27.658 +00:00 [DBG] The connection queue processing loop for 0HN252D58LMOD completed.
2024-03-15 18:23:27.658 +00:00 [DBG] Connection id "0HN252D58LMOD" stopped.
2024-03-15 18:23:27.658 +00:00 [DBG] Connection id "0HN252D58LMOD" sending FIN because: "The Socket transport's send loop completed gracefully."
```

**Comment by rummens** [comment]
For future reference, we solved this issue by mounting our root chain into the container and extending the start command with the _update-certificates_ command to load the cert into the OS. We had issues with the alpine image but the ubuntu-20 one worked just fine.
